import {
  AppWindow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  BadgePercent,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  Blocks,
  Boxes,
  Atom,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CircleDot,
  CircleUserRound,
  Code2,
  ClipboardList,
  Database,
  Download,
  FileCode2,
  FileText,
  FolderKanban,
  FolderTree,
  Gamepad2,
  GraduationCap,
  Globe,
  Headphones,
  HeartPulse,
  House,
  Image,
  LayoutDashboard,
  LayoutGrid,
  Layers3,
  Landmark,
  LogOut,
  LogIn,
  Mail,
  Megaphone,
  Menu,
  MessageSquareText,
  MessageCircle,
  Monitor,
  MonitorSmartphone,
  MousePointerClick,
  PackagePlus,
  Palette,
  MapPin,
  Phone,
  PiggyBank,
  Plus,
  ReceiptText,
  Rocket,
  Search,
  SearchCheck,
  Send,
  Settings,
  SlidersHorizontal,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Store,
  Sparkles,
  TicketCheck,
  Trash2,
  ShieldCheck,
  Workflow,
  X,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wrench,
} from 'lucide-react';

const iconMap = {
  // Core catalog / service icons
  app: AppWindow,
  atom: Atom,
  apple: Smartphone,
  badgeDollarSign: BadgeDollarSign,
  'badge-dollar-sign': BadgeDollarSign,
  brain: BrainCircuit,
  'brain-circuit': BrainCircuit,
  briefcase: BriefcaseBusiness,
  building: Building2,
  building2: Building2,
  blocks: Blocks,
  braces: Braces,
  'badge-check': BadgeCheck,
  'headphones': Headphones,
  code: Code2,
  code2: Code2,
  database: Database,
  'file-code-2': FileCode2,
  globe: Globe,
  'gamepad-2': Gamepad2,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  layers3: Layers3,
  landmark: Landmark,
  'layout-template': LayoutGrid,
  gauge: BarChart3,
  laptop: Monitor,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  megaphone: Megaphone,
  monitor: Monitor,
  'monitor-smartphone': MonitorSmartphone,
  'mouse-pointer-click': MousePointerClick,
  palette: Palette,
  search: Search,
  'search-check': SearchCheck,
  settings: Settings,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  store: Store,
  'message-square-text': MessageSquareText,
  users: Users,
  utensils: Utensils,
  wrench: Wrench,
  'circle-dot': CircleDot,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  close: X,
  gem: Blocks,
  eye: Monitor,
  lightbulb: Sparkles,
  rocket: Rocket,
  scale: ArrowLeftRight,
  target: MousePointerClick,

  // App / admin navigation icons
  analytics: BarChart3,
  accounts: Wallet,
  addOns: PackagePlus,
  'add-ons': PackagePlus,
  activityLogs: FileText,
  'activity-logs': FileText,
  backup: Download,
  budgets: PiggyBank,
  cart: ShoppingCart,
  carts: ShoppingCart,
  categories: FolderTree,
  chat: MessageSquareText,
  chats: MessageSquareText,
  clients: Users,
  content: FileText,
  configurator: SlidersHorizontal,
  customers: Users,
  dashboard: LayoutDashboard,
  deals: TicketCheck,
  expenses: ArrowLeftRight,
  finance: Banknote,
  home: House,
  'map-pin': MapPin,
  income: Banknote,
  invoices: ReceiptText,
  leads: MessageSquareText,
  mail: Mail,
  login: LogIn,
  logout: LogOut,
  media: Image,
  menu: Menu,
  'message-circle': MessageCircle,
  notifications: Bell,
  orders: ClipboardList,
  phone: Phone,
  payments: CircleDollarSign,
  portfolio: FolderKanban,
  pricing: BadgePercent,
  profile: CircleUserRound,
  projects: FolderKanban,
  quotations: ReceiptText,
  quote: ReceiptText,
  reports: BarChart3,
  refunds: CircleDollarSign,
  support: Headphones,
  settingsNav: Settings,
  services: LayoutGrid,
  'services-nav': LayoutGrid,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  tax: BadgePercent,
  transactions: ArrowLeftRight,
  usersNav: Users,
  vendors: Landmark,
  send: Send,
  user: CircleUserRound,
  'user-round': UserRound,
  'new-order': Plus,
  'new-project': Plus,
  'new-ticket': Plus,
  'new-client': Plus,
  order: ClipboardList,
  project: FolderKanban,
  ticket: TicketCheck,
  workflow: Workflow,
};

const iconChoices = [
  { key: 'code2', label: 'Code', hint: 'Web development and custom builds' },
  { key: 'monitor-smartphone', label: 'Responsive Screen', hint: 'Responsive websites and apps' },
  { key: 'smartphone', label: 'Smartphone', hint: 'Mobile app development' },
  { key: 'shopping-cart', label: 'Cart', hint: 'E-commerce and commerce workflows' },
  { key: 'shopping-bag', label: 'Shopping Bag', hint: 'Stores and product-led services' },
  { key: 'shopping-basket', label: 'Basket', hint: 'Shop and checkout experiences' },
  { key: 'layers3', label: 'Layers', hint: 'Multi-page websites and packages' },
  { key: 'layout-dashboard', label: 'Dashboard', hint: 'Admin and reporting views' },
  { key: 'folder-kanban', label: 'Projects', hint: 'Project tracking and delivery' },
  { key: 'folder-tree', label: 'Categories', hint: 'Catalog and taxonomy grouping' },
  { key: 'megaphone', label: 'Marketing', hint: 'Digital marketing and campaigns' },
  { key: 'search-check', label: 'SEO', hint: 'Search optimization and audits' },
  { key: 'palette', label: 'Design', hint: 'UI and visual design' },
  { key: 'brain-circuit', label: 'AI Automation', hint: 'Smart workflows and AI features' },
  { key: 'blocks', label: 'Build Blocks', hint: 'Custom systems and modular work' },
  { key: 'briefcase', label: 'Business', hint: 'Professional and corporate services' },
  { key: 'building2', label: 'Industry', hint: 'Industry-specific solutions' },
  { key: 'graduation-cap', label: 'Education', hint: 'Schools, institutes and learning' },
  { key: 'heart-pulse', label: 'Healthcare', hint: 'Medical and wellness businesses' },
  { key: 'store', label: 'Retail', hint: 'Retail and commerce platforms' },
  { key: 'utensils', label: 'Restaurant', hint: 'Food, menu and ordering journeys' },
  { key: 'plane', label: 'Travel', hint: 'Travel, tours and hospitality' },
  { key: 'users', label: 'Customers', hint: 'Teams, clients and community' },
  { key: 'wrench', label: 'Support', hint: 'Maintenance and ongoing care' },
  { key: 'message-square-text', label: 'Chat', hint: 'Support chat and messaging' },
  { key: 'badge-dollar-sign', label: 'Billing', hint: 'Pricing and billing systems' },
  { key: 'file-code-2', label: 'CMS', hint: 'WordPress and content systems' },
  { key: 'database', label: 'Database', hint: 'Back-end and data-driven systems' },
  { key: 'circle-dot', label: 'General', hint: 'Safe fallback for any service' },
];

const iconOptions = iconChoices.map(choice => choice.key);

export function getCatalogIcon(icon) {
  if (typeof icon === 'function') return icon;
  const key = String(icon || 'code2')
    .trim()
    .toLowerCase()
    .replace(/[_\s]+/g, '-');
  return iconMap[key] || iconMap[String(icon).trim()] || Code2;
}

export function AppIcon({ icon, size = 18, strokeWidth = 1.9, className = '', ...props }) {
  const Icon = getCatalogIcon(icon);
  return <Icon aria-hidden="true" size={size} strokeWidth={strokeWidth} className={className} {...props} />;
}

export { iconChoices, iconMap, iconOptions };
