import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';
import PageHero from '../components/PageHero';
import { useCart } from '../cart/CartContext';
import { effectivePrice, formatPrice } from '../catalog/format';

export default function Cart() {
  const { items, removeItem, updateAddons, subtotal, addonsTotal, grandTotal } = useCart();
  const changeQuantity = (item, selection, quantity) => updateAddons(item.serviceId, item.addons.map(current => current.addon.id === selection.addon.id ? { ...current, quantity: Math.max(0, quantity) } : current).filter(current => current.quantity > 0));
  return <>
    <SEO title="Service Cart" description="Review your selected SiteArvo package, add-ons and estimated final price." path="/cart" noIndex />
    <PageHero eyebrow="Your selection" title="Your Cart">Review the package, optional add-ons and price before sending your project details.</PageHero>
    <section className="section"><div className="container cart-layout">
      <div className="cart-items">{items.length ? items.map(item => { const features = (item.service.features || []).map(feature => typeof feature === 'string' ? feature : feature.name).filter(Boolean); return <article className="cart-item" key={item.serviceId}><header><div><span>{item.service.categoryTitle || 'Primary package'}</span><h2>{item.service.title}</h2></div><button type="button" className="icon-button" onClick={() => removeItem(item.serviceId)} aria-label={`Remove ${item.service.title}`}><Trash2 /></button></header><div className="cart-line"><span>Package price</span><strong>{formatPrice(effectivePrice(item.service))}</strong></div>{(item.service.pagesIncluded || features.length > 0) && <div className="cart-included"><b>Included</b>{item.service.pagesIncluded && <span>{item.service.pagesIncluded} Pages</span>}{features.slice(0, 5).map(feature => <span key={feature}>{feature}</span>)}</div>}{item.addons.length > 0 && <h3 className="cart-addon-heading">Add-ons</h3>}{item.addons.map(selection => <div className="cart-addon" key={selection.addon.id}><div><b>{selection.addon.name}</b><small>{formatPrice(effectivePrice(selection.addon))} × {selection.quantity}</small><button type="button" className="cart-remove-addon" onClick={() => changeQuantity(item, selection, 0)}>Remove</button></div><div className="quantity-control"><button type="button" onClick={() => changeQuantity(item, selection, selection.quantity - 1)} aria-label={`Reduce ${selection.addon.name}`}><Minus /></button><output aria-label={`${selection.addon.name} quantity`}>{selection.quantity}</output><button type="button" onClick={() => changeQuantity(item, selection, selection.quantity + 1)} aria-label={`Increase ${selection.addon.name}`}><Plus /></button></div><strong>{formatPrice(effectivePrice(selection.addon) * selection.quantity)}</strong></div>)}<Link className="text-link" to={`/services/${item.slug}`}>Customize package</Link></article>; }) : <div className="empty-cart"><ShoppingBag /><h2>Your service cart is empty</h2><p>Choose a configured fixed-price package to get started.</p><Link className="button" to="/pricing">Browse Packages</Link></div>}</div>
      {items.length > 0 && <aside className="order-summary"><span>Order summary</span><div><span>Package</span><strong>{formatPrice(subtotal)}</strong></div><div><span>Add-ons</span><strong>{formatPrice(addonsTotal)}</strong></div><div className="order-total"><span>Total</span><strong>{formatPrice(grandTotal)}</strong></div><p>Prices are rechecked securely against the live catalog before your enquiry is recorded.</p><Link className="button" to="/checkout">Proceed to Checkout</Link><Link className="button button--secondary" to="/services">Continue Browsing</Link></aside>}
    </div></section>
  </>;
}
