import SEO from '../components/SEO';
import PageHero from '../components/PageHero';
import { company, contactAvailability } from '../config/company';

export default function PrivacyPolicy() {
  return <><SEO title="Privacy Policy" description="Read the SiteArvo privacy policy placeholder covering website enquiries, data use and visitor rights." path="/privacy-policy" /><PageHero eyebrow="Legal" title="Privacy Policy">A clear overview of how SiteArvo may collect, use and protect information shared through this website.</PageHero><LegalNotice><h2>1. Information we may collect</h2><p>When you contact SiteArvo, we may receive information such as your name, email address, phone number, company, project requirements and any details you voluntarily include in a form or live chat conversation.</p><h2>2. Live chat</h2><p>The live chat stores the name, optional email address, messages, conversation status and limited technical information needed for security and spam prevention. A random conversation token is saved in your browser so you can return to the same conversation and receive SiteArvo replies.</p><h2>3. How information may be used</h2><p>Information may be used to respond to enquiries, prepare proposals, provide requested services, improve this website and communicate about an active business relationship.</p><h2>4. Website analytics and cookies</h2><p>If analytics or cookie-based tools are added, this section should identify those services, their purpose and the choices available to visitors.</p><h2>5. Data sharing</h2><p>SiteArvo does not intend to sell personal information. Information may be shared with service providers only where reasonably necessary to operate the website or deliver agreed services.</p><h2>6. Data retention and security</h2><p>Information should be retained only as long as necessary for the purpose for which it was collected, subject to legal and business obligations. Reasonable technical and organisational measures should be used to protect it.</p><h2>7. Your choices</h2><p>You may contact SiteArvo to ask about, correct or request deletion of personal information, subject to applicable obligations and exemptions.</p><h2>8. External links</h2><p>This website may link to third-party services. SiteArvo is not responsible for the privacy practices or content of those third-party websites.</p><h2>9. Policy updates</h2><p>This policy may be updated as the website, services or legal requirements change. Add an effective date before publishing.</p><h2>10. Contact</h2>{contactAvailability.email ? <p>Privacy questions can be directed to <a href={`mailto:${company.email}`}>{company.email}</a>.</p> : <p>Business contact details must be added in the central company configuration before launch.</p>}</LegalNotice></>;
}

function LegalNotice({ children }) { return <section className="section"><div className="container legal-layout"><aside><b>Before launch</b><p>Replace placeholder contact details and have this policy reviewed for your business, tools and applicable laws.</p></aside><article className="legal-copy"><div className="legal-disclaimer">Template notice: This placeholder is for general informational purposes and is not legal advice.</div>{children}</article></div></section>; }
export { LegalNotice };
